blog/config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  devise_for :users
  devise_scope :user do
   get "sign_in", :to => "devise/sessions#new"
   get "sign_out", :to => "devise/sessions#destroy"
  end
  
  resources :posts
  resources :categories

  get "home/index"

  root :to => "home#index"

end

blog/app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :posts
  
  attr_accessible :nome, :slug
  
  validates_presence_of :nome
end

blog/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data
  
  validates_presence_of :data
end

blog/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

blog/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
  
  before_save :set_category
  
  belongs_to :category
  
  attr_accessible :body, :category_id, :titulo
  
  validates_presence_of :titulo, :body
  
  
  def set_category
    if category_id.nil?
      self.category_id = 1
    end
  end
  
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }      
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
      format.js      
    end
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:category).paginate(:page => params[:page], :per_page => 1)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.js
    end
    
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
      format.js
    end
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
  def show_item_url(url)
    link_to raw('<i class="icon-info-sign"></i>'), url, :class => "btn btn-small btn-primary", :tip => "tooltip", :title => "Ver item"
  end
  
  def new_item_url(url)
    link_to raw('<i class="icon-pencil"></i>'), url, :class => "btn btn-small", :tip => "tooltip", :title => "Nova item"
  end
  
  def edit_item_url(url)
    link_to raw('<i class="icon-edit"></i>'), url, :class => "btn btn-small btn-primary", :tip => "tooltip", :title => "Editar item"
  end
  
  def delete_item_url(url)
    link_to raw('<i class="icon-trash"></i>'), 
            url, 
            method: :delete, 
            data: { confirm: 'Are you sure?' },
            remote: true, 
            :class => "btn btn-small btn-primary", 
            :tip => "tooltip", 
            :title => "Deletar item"
  end
  
  def paginate(collection, params= {})
    will_paginate collection, params.merge(:renderer => RemoteLinkPaginationHelper::LinkRenderer)
  end
end

blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/remote_link_pagination_helper.rb
module RemoteLinkPaginationHelper
  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    def link(text, target, attributes = {})
      attributes['data-remote'] = true
      super
    end
  end
end

blog/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar", :class => "btn" %>
  </div>
<% end %>

blog/app/views/categories/destroy.js.erb
$("#cat-<%= @category.id %>").fadeOut('slow').remove();

blog/app/views/categories/edit.html.erb
<h1>Editar categoria</h1>

<%= render 'form' %>

<%= link_to 'Voltar', categories_path, :class => "btn btn-warning" %>

blog/app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table class="table table-striped">
  <tr>
    <th>Nome</th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr id="cat-<%= category.id %>">
    <td><%= category.nome %></td>
    <td>
      <%= show_item_url category %>
      <%= edit_item_url edit_category_path(category) %>
      <%= delete_item_url category %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova categoria', new_category_path, :class => "btn" %>

blog/app/views/categories/new.html.erb
<h3>Nova categoria</h3>

<%= render 'form' %>

<%= link_to 'Voltar', categories_path, :class => "btn btn-warning" %>

blog/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @category.nome %>
</p>

<p>
  <b>Slug:</b>
  <%= @category.slug %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

blog/app/views/home/index.html.erb
<%= render :partial => "posts/post", :collection => @posts || "Não há nenhum post cadastrado" %>

<%= paginate @posts %>

blog/app/views/home/index.js.erb
$("#posts").html("<%= escape_javascript(render(:partial => "posts/post", :collection => @posts)) %>");
$("#posts").append("<%= escape_javascript(paginate @posts) %>")

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="#">Blog</a>
        <ul class="nav">
          <li class="active"><a href="<%= root_url %>">Início</a></li>
          <% if user_signed_in? %>
          <li><%= link_to "Posts",  posts_url %></li>
          <li><%= link_to "Categorias",  categories_url %></li>
          <li><%= link_to "Sair", sign_out_url %></li>          
          <% else %>
            <li><%= link_to "Acessar", sign_in_url %></li>
          <% end %>
        </ul>
      </div>
    </div>
</div>
<div class="container">
    <div id="posts" class="span8">
        <%= yield %>
    </div>
    
    <div id="caterias" class="span4">
        
    </div>
</div>

</body>
</html>

blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :texto %><br />
    <%= f.cktext_area :body, :ckeditor => {:language => "pt-br", :toolbar => "mini"} %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= collection_select(:post, :category_id, Category.all, :id, :nome) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/posts/_post.html.erb
<div class="post">
  <% if user_signed_in? %>
    <%= link_to 'Editar post', edit_post_path(post), :class => "btn" %>
  <% end %>
  <h3><%= post.titulo %></h3>

  <% if post.category %>
    <div class="categoria"><p>Categoria: <%= post.category.nome %></p></div>
  <% end %>

  <div class="body">
    <%= post.body.html_safe %>  
  </div>
  <p></p>
</div>

blog/app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").fadeOut('slow').remove();

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<h3>Posts</h3>

<table class="table table-striped">
  <tr>
    <th>Titulo</th>
    <th>Categoria</th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr id="post-<%= post.id %>">
    <td><%= post.titulo %></td>
    <td><%= post.category.nome %></td>
    <td>
      <%= show_item_url post %>
      <%= edit_item_url edit_post_path(post) %>
      <%= delete_item_url post %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo post', new_post_path, :class => "btn" %>

blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @post.titulo %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body.html_safe %>
</p>

<p>
  <b>Category:</b>
  <%= @post.category.nome %>
</p>


<%= link_to 'Edit', edit_post_path(@post), :class => "btn" %> |
<%= link_to 'Back', posts_path, :class => "btn" %>